<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PCOS-1606141414" name="case3" tests="9" failures="1" timestamp="24 May 2017 05:59:11 GMT" time="148.084" errors="0">
  <testcase name="test1" time="17.882" classname="TestCases.Case3"/>
  <testcase name="test2" time="86.197" classname="TestCases.Case3"/>
  <testcase name="test3" time="19.797" classname="TestCases.Case3"/>
  <testcase name="test4" time="19.912" classname="TestCases.Case3"/>
  <testcase name="test5" time="0.0" classname="TestCases.Case3">
    <failure type="java.lang.RuntimeException" message="fail....">
      <![CDATA[java.lang.RuntimeException: fail....
	at TestCases.Case3.test5(Case3.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- test5 -->
  <testcase name="test6" time="0.0" classname="TestCases.Case3"/>
  <testcase name="verifyUser" time="0.0" classname="TestCases.Case3"/>
  <testcase name="verifyUser" time="0.0" classname="TestCases.Case3"/>
  <testcase name="verifyUser" time="0.0" classname="TestCases.Case3"/>
</testsuite> <!-- case3 -->
